### PR TITLE
Add installation instructions to ReadMe

### PR DESCRIPTION
**Pull request by Clashsoft**
Snippets taken from https://mvnrepository.com/artifact/net.harawata/appdirs/1.2.1.
The version number needs to be updated every time there is a new release.

### CODE REVIEW

**Comment by Clashsoft** [comment]
Perhaps it makes sense to move the content of the `Requirements` section (Java 6 + JNA) up into the new section. However, I am unsure about the wording:

> AppDirs requires [...] Java Native Access (JNA) as its dependency.

Does that mean it needs to be added separately, or is it already added as a transitive dependency?

**Comment by harawata** [comment]
Thank you for the PR, @Clashsoft !

'Installation' seems inappropriate for this library.
I'll just add a 'download' section that includes links to the following pages with brief explanation.

- https://mvnrepository.com/artifact/net.harawata/appdirs
- https://github.com/harawata/appdirs/releases

How does that sound?

JNA is a [compile](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope) scope dependency which means if you use a dependency management tool like Maven or Gradle, it may be added implicitly.
If you don't use dependency management tool, you have to add JNA manually.

**Comment by Clashsoft** [comment]
Thanks for the feedback, I updated my changes 😄 I kept the snippets in case mvnrepository is down or unavailable.

**Comment by harawata** [comment]
Thanks for the update, @Clashsoft !

Assuming that your goal is to help users who are relatively new to Java development, I decided to add 'Quickstart' 
section instead.
I've added a new commit on your branch. Hope that was OK.

A few notes:

- As I'm lazy, I would like to avoid updating version number on every release, so no snippets. Sorry! :D
- 'Requirements' section is kind of important for Java libraries, IMHO.

If there is any other area you want to improve, please let me know!

**Comment by Clashsoft** [comment]
Yes, that looks good! But I'd probably put the section between Overview and the code examples. Logically you'd need to download before you could use them and it's also hard to find all the way at the bottom imo.

**Comment by harawata** [comment]
I would prefer seeing the examples before installing, but the order you proposed seems popular, so I took your advice.
Thank you again for your contributions!

**Pull request merged**
